name: Sync to Hugging Face Hub
on:
  push:
    branches: [automation-engine] # Triggers when changes hit this branch
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://Avk44:$HF_TOKEN@huggingface.co/spaces/Avk44/torbox-manager HEAD:refs/heads/main
